---

- name: Create database for neutron
  mysql_db:
    login_host: "{{ os_management_ip }}"
    login_password: "{{os_root_mysql_pass}}"
    login_user: root
    name: neutron
    state: present

- name: Grant privilleges to neutron user
  mysql_user:
    login_user: root
    login_password: "{{ os_root_mysql_pass }}"
    name: neutron
    password: "{{ neutron_db_pass }}"
    priv: 'neutron.*:ALL'
    host: "{{ item }}"
    state: present
  with_items:
    - 'localhost'
    - '%'

- name: Create user neutron
  os_user:
    name: neutron
    domain: default
    password: "{{ neutron_user_pass }}"
    state: present
    update_password: on_create


- name: Add neutron user to admin role
  os_user_role:
    role: admin
    user: neutron
    project: service
    state: present


- name: Create service neutron
  os_keystone_service:
    name: neutron
    service_type: network
    description: "OpenStack Networking"
    state: present

- name: Create endpoints for neutron
  os_keystone_endpoint: 
    service: neutron
    url: "http://controller:9696"
    region: RegionOne
    endpoint_interface: "{{ item }}"
    state: present
  with_items:
    - "public"
    - "internal"
    - "admin"


- name: Install neutron components
  yum:
    name:
      - openstack-neutron
      - openstack-neutron-ml2
      - openstack-neutron-linuxbridge
      - ebtables
    state: present
  register: neutron_pack_status
  
- name: Configure neutron provider networks
  ini_file: 
    path: "/etc/neutron/neutron.conf"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: 'DEFAULT', option: 'core_plugin', value: 'ml2' }
    - { section: 'DEFAULT', option: 'service_plugins', value: 'router' }
    - { section: 'DEFAULT', option: 'allow_overlapping_ips', value: 'true' }
    - { section: 'DEFAULT', option: 'transport_url', value: "rabbit://openstack:{{ os_rabbit_mq_openstack_pass }}@controller" }
    - { section: 'DEFAULT', option: 'auth_strategy', value: 'keystone' }
    - { section: 'DEFAULT', option: 'notify_nova_on_port_status_changes', value: 'true' }
    - { section: 'DEFAULT', option: 'notify_nova_on_port_data_changes', value: 'true' }
    - { section: 'database', option: 'connection', value: 'mysql+pymysql://neutron:{{ neutron_db_pass }}@controller/neutron' }    
    - { section: 'keystone_authtoken', option: 'auth_uri', value: 'http://controller:5000' }
    - { section: 'keystone_authtoken', option: 'auth_url', value: 'http://controller:35357' }
    - { section: 'keystone_authtoken', option: 'memcached_servers', value: 'controller:11211' }
    - { section: 'keystone_authtoken', option: 'auth_type', value: 'password' }
    - { section: 'keystone_authtoken', option: 'project_domain_name', value: 'default' }
    - { section: 'keystone_authtoken', option: 'user_domain_name', value: 'default' }
    - { section: 'keystone_authtoken', option: 'project_name', value: 'service' }
    - { section: 'keystone_authtoken', option: 'username', value: 'neutron' }
    - { section: 'keystone_authtoken', option: 'password', value: "{{ neutron_user_pass }}" }
    - { section: 'nova', option: 'auth_url', value: 'http://controller:35357' }
    - { section: 'nova', option: 'auth_type', value: 'password' }
    - { section: 'nova', option: 'project_domain_name', value: 'default' }
    - { section: 'nova', option: 'user_domain_name', value: 'default' }
    - { section: 'nova', option: 'region_name', value: 'RegionOne' }
    - { section: 'nova', option: 'project_name', value: 'service' }
    - { section: 'nova', option: 'username', value: 'nova' }
    - { section: 'nova', option: 'password', value: "{{ nova_user_pass }}" }
    - { section: 'oslo_concurrency', option: 'lock_path', value: "/var/lib/neutron/tmp" }


- name: Configure ml2 plugin
  ini_file:
    path: "/etc/neutron/plugins/ml2/ml2_conf.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: 'ml2', option: 'type_drivers', value: 'flat,vlan,vxlan' }
    - { section: 'ml2', option: 'tenant_network_types', value: 'vxlan' }
    - { section: 'ml2', option: 'mechanism_drivers', value: 'linuxbridge, l2population' }
    - { section: 'ml2', option: 'extension_drivers', value: 'port_security' }
    - { section: 'ml2_type_flat', option: 'flat_networks', value: 'provider' }
    - { section: 'ml2_type_vxlan', option: 'vni_ranges', value: '1:1000' }
    - { section: 'securitygroup', option: 'enable_ipset', value: 'true' }


- name: Configure linux bridge agent
  ini_file:
    path: "/etc/neutron/plugins/ml2/linuxbridge_agent.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: 'linux_bridge', option: 'physical_interface_mappings', value: 'provider:{{ ansible_interfaces[2] }}' }
    - { section: 'vxlan', option: 'enable_vxlan', value: 'false' }
    - { section: 'vxlan', option: 'local_ip', value: '{{ os_management_ip }}' }
    - { section: 'vxlan', option: 'l2_population', value: 'true' }
    - { section: 'securitygroup', option: 'enable_security_group', value: 'true' }
    - { section: 'securitygroup', option: 'firewall_driver', value: 'neutron.agent.linux.iptables_firewall.IptablesFirewallDriver' }

- name: Configure DHCP agent
  ini_file:
    path: "/etc/neutron/dhcp_agent.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: 'DEFAULT', option: 'interface_driver', value: 'linuxbridge' }
    - { section: 'DEFAULT', option: 'dhcp_driver', value: 'neutron.agent.linux.dhcp.Dnsmasq' }
    - { section: 'DEFAULT', option: 'enable_isolated_metadata', value: 'true' }

- name: Configure layer-3 agent
  ini_file:
    path: "/etc/neutron/l3_agent.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: 'DEFAULT', option: 'interface_driver', value: 'linuxbridge' }
      

- name: Configure metadata agent
  ini_file:
    path: "/etc/neutron/metadata_agent.ini"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: 'DEFAULT', option: 'nova_metadata_host', value: 'controller' }
    - { section: 'DEFAULT', option: 'metadata_proxy_shared_secret', value: '{{ metadata_secret_pass }}' }

- name: Configure compute service to use networking
  ini_file:
    path: "/etc/nova/nova.conf"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:  
    - { section: 'neutron', option: 'auth_url', value: 'http://controller:9696' }
    - { section: 'neutron', option: 'auth_type', value: 'password' }
    - { section: 'neutron', option: 'project_domain_name', value: 'default' }
    - { section: 'neutron', option: 'user_domain_name', value: 'default' }
    - { section: 'neutron', option: 'region_name', value: 'RegionOne' }
    - { section: 'neutron', option: 'project_name', value: 'service' }
    - { section: 'neutron', option: 'username', value: 'neutron' }
    - { section: 'neutron', option: 'password', value: "{{ neutron_user_pass }}" }
    - { section: 'neutron', option: 'service_metadata_proxy', value: 'true' }
    - { section: 'neutron', option: 'metadata_proxy_shared_secret', value: '{{ metadata_secret_pass }}' }

- name: Make symbolic link
  file:
    src: /etc/neutron/plugins/ml2/ml2_conf.ini
    dest: /etc/neutron/plugin.ini
    state: link
  ignore_errors: true

- name: Populate the database
  become: yes
  become_user: neutron
  shell: "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head"
  #when: neutron_pack_status.changed

- name: Restart compute-aoi service
  systemd:
    name: openstack-nova-api
    state: restarted

- name: Enable and restart nova services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - neutron-server
    - neutron-linuxbridge-agent
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-l3-agent

