---

- name: Install neutron components
  yum:
    name:
      - openstack-neutron-linuxbridge
      - ebtables
      - ipset
    state: present
  register: neutron_copmute_pack_status
  
- name: Configure neutron compute node
  ini_file: 
    path: "/etc/neutron/neutron.conf"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: 'DEFAULT', option: 'transport_url', value: "rabbit://openstack:{{ os_rabbit_mq_openstack_pass }}@controller" }
    - { section: 'DEFAULT', option: 'auth_strategy', value: 'keystone' }    
    - { section: 'keystone_authtoken', option: 'auth_uri', value: 'http://controller:5000' }
    - { section: 'keystone_authtoken', option: 'auth_url', value: 'http://controller:35357' }
    - { section: 'keystone_authtoken', option: 'memcached_servers', value: 'controller:11211' }
    - { section: 'keystone_authtoken', option: 'auth_type', value: 'password' }
    - { section: 'keystone_authtoken', option: 'project_domain_name', value: 'default' }
    - { section: 'keystone_authtoken', option: 'user_domain_name', value: 'default' }
    - { section: 'keystone_authtoken', option: 'project_name', value: 'service' }
    - { section: 'keystone_authtoken', option: 'username', value: 'neutron' }
    - { section: 'keystone_authtoken', option: 'password', value: "{{ neutron_user_pass }}" }
    - { section: 'oslo_concurrency', option: 'lock_path', value: "/var/lib/neutron/tmp" }



- name: Configure compute service to use networking
  ini_file:
    path: "/etc/nova/nova.conf"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:  
    - { section: 'neutron', option: 'auth_url', value: 'http://controller:9696' }
    - { section: 'neutron', option: 'auth_type', value: 'password' }
    - { section: 'neutron', option: 'project_domain_name', value: 'default' }
    - { section: 'neutron', option: 'user_domain_name', value: 'default' }
    - { section: 'neutron', option: 'region_name', value: 'RegionOne' }
    - { section: 'neutron', option: 'project_name', value: 'service' }
    - { section: 'neutron', option: 'username', value: 'neutron' }
    - { section: 'neutron', option: 'password', value: "{{ neutron_user_pass }}" }


- name: Restart nova-compute service
  systemd:
    name: openstack-nova-compute
    state: restarted

- name: Enable and restart  services
  systemd:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
    - neutron-linuxbridge-agent

