---

- name: Install nova compute
  yum:
    name: openstack-nova-compute
    state: present
  register: nova_comp_pack_status

- name: Configure nova
  ini_file:
    path: "/etc/nova/nova.conf"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: 'DEFAULT', option: 'enabled_apis', value: 'osapi_compute,metadata' }
    - { section: 'DEFAULT', option: 'transport_url', value: 'rabbit://openstack:{{ os_rabbit_mq_openstack_pass }}@controller' }
    - { section: 'DEFAULT', option: 'my_ip', value: "{{ os_management_ip }}" }
    - { section: 'DEFAULT', option: 'use_neutron', value: 'True' }
    - { section: 'DEFAULT', option: 'firewall_driver', value: 'nova.virt.firewall.NoopFirewallDriver' }
    - { section: 'api', option: 'auth_strategy', value: 'keystone' }
    - { section: 'keystone_authtoken', option: 'auth_uri', value: 'http://controller:5000' }
    - { section: 'keystone_authtoken', option: 'auth_url', value: 'http://controller:35357' }
    - { section: 'keystone_authtoken', option: 'memcached_servers', value: 'controller:11211' }
    - { section: 'keystone_authtoken', option: 'auth_type', value: 'password' }
    - { section: 'keystone_authtoken', option: 'project_domain_name', value: 'default' }
    - { section: 'keystone_authtoken', option: 'user_domain_name', value: 'default' }
    - { section: 'keystone_authtoken', option: 'project_name', value: 'service' }
    - { section: 'keystone_authtoken', option: 'username', value: 'nova' }
    - { section: 'keystone_authtoken', option: 'password', value: "{{ nova_user_pass }}" }
    - { section: 'vnc', option: 'enabled ', value: 'true' }
    - { section: 'vnc', option: 'vncserver_listen', value: '0.0.0.0' }
    - { section: 'vnc', option: 'vncserver_proxyclient_address', value: '$my_ip' }
    - { section: 'vnc', option: 'novncproxy_base_url', value: 'http://controller:6080/vnc_auto.html' }
    - { section: 'glance', option: 'api_servers', value: 'http://controller:9292' }
    - { section: 'oslo_concurrency', option: 'lock_path', value: '/var/lib/nova/tmp' }
    - { section: 'placement', option: 'os_region_name', value: 'RegionOne' }
    - { section: 'placement', option: 'project_domain_name', value: 'Default' }
    - { section: 'placement', option: 'project_name', value: 'service' }
    - { section: 'placement', option: 'auth_type', value: 'password' }
    - { section: 'placement', option: 'user_domain_name', value: 'default' }
    - { section: 'placement', option: 'auth_url', value: 'http://controller:35357/v3' }
    - { section: 'placement', option: 'username', value: 'placement' }
    - { section: 'placement', option: 'password', value: "{{ placement_user_pass }}" }

- name: Check hardware acceleration
  shell: "egrep -c '(vmx|svm)' /proc/cpuinfo | cat"
  register: virt_status

- name: Configure using qemu
  ini_file:
    path: "/etc/nova/nova.conf"
    section: libvirt
    option: "virt_type"
    value: "qemu"
  when: virt_status.rc == 0

- name: Enable restart nova-compute
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - libvirtd
    - openstack-nova-compute


- name: Check compute node
  shell: "openstack compute service list --service nova-compute"
  register: comp_hosts_status

- debug: var=comp_hosts_status.stdout_lines

- name: Discover compute hosts
  become: yes
  become_user: nova
  shell: "nova-manage cell_v2 discover_hosts"

